### ISSUE TITLE
browser support for es6 features

### ISSUE THREAD

**Issue by atomanyih** [johno/is-blank#2]
https://github.com/johnotander/is-blank/commit/663489c9e811cba484e07c530aa09ab9092cf2b5 broke support for older browsers :(

Arrow functions in particular are breaking for us on IE 11, Safari 9 and PhantomJS

http://caniuse.com/#feat=arrow-functions
http://caniuse.com/#feat=const

**Comment by johnotander** [comment]
Oh noes! Will revert these changes in just a moment.

**Comment by johno** [comment]
This should be fixed in `is-blank@2.1.0`. Thanks for opening the issue!
